language: go

go:
  - "1.9.x"
  - "1.10.x"

before_install:
  - go get -v github.com/stretchr/testify

script:
  - cd $TRAVIS_BUILD_DIR; bash run_test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
