language: go

os:
  - linux
  - osx
  
compiler: gcc

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10.2

go:
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"

before_install:
  - go get -v github.com/stretchr/testify

script:
  - cd $TRAVIS_BUILD_DIR; bash run_test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
